feature: crud question
felipe2g/stackti-app pull request #12
Opened 2022-12-01 22:43 UTC by Samuell0003

2022-12-01 22:56 UTC, felipe2g requested changes
ajustes

2022-12-01 22:56 UTC, felipe2g commented on src/main/java/com/stackti/server/question/Question.java
> +    private LocalDateTime data;
alterar nome para date

2022-12-01 22:56 UTC, felipe2g commented on src/main/java/com/stackti/server/question/Question.java
> +    public String dataFormat() {
retirar a função, ou alterar o nome para getDate

2022-12-01 22:56 UTC, felipe2g commented on src/main/java/com/stackti/server/question/QuestionController.java
> +    @GetMapping("questionNew")
alterar rota para `/question/new`

2022-12-01 22:56 UTC, felipe2g commented on src/main/java/com/stackti/server/question/QuestionController.java
> +    @PostMapping("questioNew")
alterar rota para `/question/new`

2022-12-01 22:56 UTC, felipe2g commented on src/main/java/com/stackti/server/question/QuestionController.java
> +        return "redirect:/questionNew";
alterar aqui também

2022-12-01 22:56 UTC, felipe2g commented on src/main/java/com/stackti/server/question/QuestionRepository.java
> +                res.getTimestamp("question_data").toLocalDateTime(),
esse campo ainda existe?

2022-12-01 22:56 UTC, felipe2g commented on src/main/resources/static/style.css
> +    background-color: DodgerBlue;
essa cor existe?

2022-12-08 21:56 UTC, joao-vitorg approved these changes

2022-12-13 00:01 UTC, felipe2g approved these changes

2022-12-13 00:01 UTC, merged